import { describe, it, expect } from 'vitest';
import { ProjectData, CreateProjectData, UpdateProjectData } from '@context-forge/core';

describe('Task File Data Structure Tests', () => {
  // Test data structure compatibility and serialization

  const generateTaskFileName = (slice: string): string => {
    if (!slice) return '';
    const sliceMatch = slice.match(/^(\d+)-slice\.(.+)$/);
    if (sliceMatch) {
      const [, sliceNumber, sliceName] = sliceMatch;
      return `${sliceNumber}-tasks.${sliceName}`;
    }
    return slice.replace('slice', 'tasks');
  };

  it('should include fileTasks in ProjectData structure for persistence', () => {
    // Test that ProjectData includes fileTasks field
    const projectData: ProjectData = {
      id: 'test-project',
      name: 'Test Project',
      template: 'react',
      fileSlice: '031-slice.hero-section',
      fileTasks: '031-tasks.hero-section',
      instruction: 'implementation',
      workType: 'continue',
      isMonorepo: false,
      customData: {},
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    // Verify fileTasks is properly typed and accessible
    expect(projectData.fileTasks).toBe('031-tasks.hero-section');
    expect(typeof projectData.fileTasks).toBe('string');

    // Test JSON serialization/deserialization (simulating storage persistence)
    const serialized = JSON.stringify(projectData);
    const deserialized: ProjectData = JSON.parse(serialized);

    expect(deserialized.fileTasks).toBe('031-tasks.hero-section');
  });

  it('should support CreateProjectData with optional fileTasks', () => {
    // Test CreateProjectData type compatibility
    const createData: CreateProjectData = {
      name: 'New Project',
      template: 'vue',
      fileSlice: '055-slice.dashboard',
      fileTasks: '055-tasks.dashboard', // Optional field
      isMonorepo: false
    };

    expect(createData.fileTasks).toBe('055-tasks.dashboard');

    // Test CreateProjectData without fileTasks (should be valid)
    const createDataWithoutFileTasks: CreateProjectData = {
      name: 'New Project 2',
      template: 'angular',
      fileSlice: '066-slice.profile',
      isMonorepo: false
      // fileTasks omitted (should be valid due to optional)
    };

    expect(createDataWithoutFileTasks.fileTasks).toBeUndefined();

    // Verify fallback generation works
    const fallbackTaskFile = generateTaskFileName(createDataWithoutFileTasks.fileSlice);
    expect(fallbackTaskFile).toBe('066-tasks.profile');
  });

  it('should support UpdateProjectData with fileTasks updates', () => {
    // Test UpdateProjectData type compatibility for fileTasks updates
    const updateData: UpdateProjectData = {
      fileTasks: 'updated-custom-task-file'
    };

    expect(updateData.fileTasks).toBe('updated-custom-task-file');

    // Test partial update with multiple fields including fileTasks
    const partialUpdate: UpdateProjectData = {
      name: 'Updated Project Name',
      fileSlice: '777-slice.updated',
      fileTasks: 'custom-task-name'
    };

    expect(partialUpdate.fileTasks).toBe('custom-task-name');
    expect(partialUpdate.name).toBe('Updated Project Name');
    expect(partialUpdate.fileSlice).toBe('777-slice.updated');
  });

  it('should demonstrate fileTasks persistence patterns', () => {
    // Test the data transformation patterns used in the app

    // Pattern 1: Auto-generation from fileSlice
    const slice1 = '300-slice.api-integration';
    const autoGenerated1 = generateTaskFileName(slice1);
    expect(autoGenerated1).toBe('300-tasks.api-integration');

    // Pattern 2: User enters custom fileTasks value
    const userCustom = 'my-special-task-file-name';

    // Pattern 3: Simulate form data persistence with both patterns
    const projectWithAutoGen: ProjectData = {
      id: 'project-1',
      name: 'Auto Project',
      template: 'react',
      fileSlice: slice1,
      fileTasks: autoGenerated1,
      instruction: 'implementation',
      workType: 'continue',
      isMonorepo: false,
      customData: {},
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    const projectWithCustom: ProjectData = {
      id: 'project-2',
      name: 'Custom Project',
      template: 'vue',
      fileSlice: '400-slice.user-auth',
      fileTasks: userCustom,
      instruction: 'implementation',
      workType: 'continue',
      isMonorepo: false,
      customData: {},
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    // Simulate JSON persistence (what actually happens in storage)
    const serialized1 = JSON.stringify(projectWithAutoGen);
    const serialized2 = JSON.stringify(projectWithCustom);

    const restored1: ProjectData = JSON.parse(serialized1);
    const restored2: ProjectData = JSON.parse(serialized2);

    // Verify persistence maintains fileTasks values
    expect(restored1.fileTasks).toBe('300-tasks.api-integration');
    expect(restored2.fileTasks).toBe('my-special-task-file-name');

    // This demonstrates that fileTasks values will persist correctly across sessions
  });
});
